<!doctype html>
<html lang="">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test Results Report - Post Bank employee details and validate Response</title>

    <link href="reportng.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="meta">
Generated by <a href="http://www.testng.org" target="_blank">TestNG</a> with <a href="https://github.com/testng-team/reportng" target="_blank">ReportNG</a>
at 01:47 IST on Friday 19 April 2024
    <br/><span
    id="systemInfo">sunilk@MAVBNG082112&nbsp;/&nbsp;Java 17.0.10 (Oracle Corporation)&nbsp;/&nbsp;Windows 10 10.0 (amd64)</span>
</div>
<h1>Post Bank employee details and validate Response</h1>

<p>
    <a href="index.html">Suites</a>
        &#183; <a href="output.html">Log Output</a>
</p>

<p>Test duration
    : 4.913s</p>


    <table class="resultsTable">
        <tr>
            <th colspan="3" class="header failed">Failed Tests</th>
        </tr>
            <tr>
                <td class="group" colspan="3">TestNGAssignment.Assignment002</td>
            </tr>
    <tr>
        <td class="method">
                create_new_BankEmployee
        </td>
        <td class="duration">
            2.303s
        </td>
        <td class="result">
            <!-- Display the dependencies for skipped test methods -->

                <i>Method arguments: </i>
                <span class="arguments">
                    "https://api.restful-api.dev/objects", "Sam Sundar", "2024", "03-03-1985", "Kolkata 1234", "10000"
                </span>
                <br/>

            <!-- Show logger output for the test -->

                <a href="javascript:toggleElement('exception-0', 'block')"
                   title="Click to expand/collapse">
                    <b>java.lang.AssertionError: expected [200] but found [405]</b>
                </a>
                <br/>
                <div class="stackTrace" id="exception-0">
                        org.testng.Assert.fail(Assert.java:111)<br/>
                        org.testng.Assert.failNotEquals(Assert.java:1578)<br/>
                        org.testng.Assert.assertEqualsImpl(Assert.java:150)<br/>
                        org.testng.Assert.assertEquals(Assert.java:132)<br/>
                        org.testng.Assert.assertEquals(Assert.java:1419)<br/>
                        org.testng.Assert.assertEquals(Assert.java:1383)<br/>
                        org.testng.Assert.assertEquals(Assert.java:1429)<br/>
                        TestNGAssignment.Assignment002.create_new_BankEmployee(Assignment002.java:37)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/>
                        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
                        java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>
                        org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)<br/>
                        org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)<br/>
                        org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)<br/>
                        org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)<br/>
                        org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)<br/>
                        java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
                        org.testng.TestRunner.privateRun(TestRunner.java:819)<br/>
                        org.testng.TestRunner.run(TestRunner.java:619)<br/>
                        org.testng.SuiteRunner.runTest(SuiteRunner.java:443)<br/>
                        org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)<br/>
                        org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)<br/>
                        org.testng.SuiteRunner.run(SuiteRunner.java:336)<br/>
                        org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
                        org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)<br/>
                        org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)<br/>
                        org.testng.TestNG.runSuitesLocally(TestNG.java:1228)<br/>
                        org.testng.TestNG.runSuites(TestNG.java:1134)<br/>
                        org.testng.TestNG.run(TestNG.java:1101)<br/>
                        com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)<br/>
                        com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)<br/>
                </div>
        </td>
    </tr>
    <tr>
        <td class="method">
                delete_BankEmployee_record
        </td>
        <td class="duration">
            0.850s
        </td>
        <td class="result">
            <!-- Display the dependencies for skipped test methods -->

                <i>Method arguments: </i>
                <span class="arguments">
                    "https://api.restful-api.dev/objects"
                </span>
                <br/>

            <!-- Show logger output for the test -->

                <a href="javascript:toggleElement('exception-1', 'block')"
                   title="Click to expand/collapse">
                    <b>java.lang.AssertionError: expected [200] but found [405]</b>
                </a>
                <br/>
                <div class="stackTrace" id="exception-1">
                        org.testng.Assert.fail(Assert.java:111)<br/>
                        org.testng.Assert.failNotEquals(Assert.java:1578)<br/>
                        org.testng.Assert.assertEqualsImpl(Assert.java:150)<br/>
                        org.testng.Assert.assertEquals(Assert.java:132)<br/>
                        org.testng.Assert.assertEquals(Assert.java:656)<br/>
                        org.testng.Assert.assertEquals(Assert.java:666)<br/>
                        TestNGAssignment.Assignment002.delete_BankEmployee_record(Assignment002.java:133)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/>
                        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
                        java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>
                        org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)<br/>
                        org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)<br/>
                        org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)<br/>
                        org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)<br/>
                        org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)<br/>
                        java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
                        org.testng.TestRunner.privateRun(TestRunner.java:819)<br/>
                        org.testng.TestRunner.run(TestRunner.java:619)<br/>
                        org.testng.SuiteRunner.runTest(SuiteRunner.java:443)<br/>
                        org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)<br/>
                        org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)<br/>
                        org.testng.SuiteRunner.run(SuiteRunner.java:336)<br/>
                        org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
                        org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)<br/>
                        org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)<br/>
                        org.testng.TestNG.runSuitesLocally(TestNG.java:1228)<br/>
                        org.testng.TestNG.runSuites(TestNG.java:1134)<br/>
                        org.testng.TestNG.run(TestNG.java:1101)<br/>
                        com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)<br/>
                        com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)<br/>
                </div>
        </td>
    </tr>
    <tr>
        <td class="method">
                get_BankEmployeeDetails_to_Validate
        </td>
        <td class="duration">
            0.829s
        </td>
        <td class="result">
            <!-- Display the dependencies for skipped test methods -->

                <i>Method arguments: </i>
                <span class="arguments">
                    "https://api.restful-api.dev/objects", "Sam Sundar", "2024", "03-03-1985", "Kolkata 1234", "10000"
                </span>
                <br/>

            <!-- Show logger output for the test -->

                <a href="javascript:toggleElement('exception-2', 'block')"
                   title="Click to expand/collapse">
                    <b>java.lang.AssertionError: expected [200] but found [405]</b>
                </a>
                <br/>
                <div class="stackTrace" id="exception-2">
                        org.testng.Assert.fail(Assert.java:111)<br/>
                        org.testng.Assert.failNotEquals(Assert.java:1578)<br/>
                        org.testng.Assert.assertEqualsImpl(Assert.java:150)<br/>
                        org.testng.Assert.assertEquals(Assert.java:132)<br/>
                        org.testng.Assert.assertEquals(Assert.java:656)<br/>
                        org.testng.Assert.assertEquals(Assert.java:666)<br/>
                        TestNGAssignment.Assignment002.get_BankEmployeeDetails_to_Validate(Assignment002.java:58)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/>
                        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
                        java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>
                        org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)<br/>
                        org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)<br/>
                        org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)<br/>
                        org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)<br/>
                        org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)<br/>
                        java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
                        org.testng.TestRunner.privateRun(TestRunner.java:819)<br/>
                        org.testng.TestRunner.run(TestRunner.java:619)<br/>
                        org.testng.SuiteRunner.runTest(SuiteRunner.java:443)<br/>
                        org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)<br/>
                        org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)<br/>
                        org.testng.SuiteRunner.run(SuiteRunner.java:336)<br/>
                        org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
                        org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)<br/>
                        org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)<br/>
                        org.testng.TestNG.runSuitesLocally(TestNG.java:1228)<br/>
                        org.testng.TestNG.runSuites(TestNG.java:1134)<br/>
                        org.testng.TestNG.run(TestNG.java:1101)<br/>
                        com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)<br/>
                        com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)<br/>
                </div>
        </td>
    </tr>
    <tr>
        <td class="method">
                putCallToUpdateAddressOfBankEmployeeDetails_Validation
        </td>
        <td class="duration">
            0.917s
        </td>
        <td class="result">
            <!-- Display the dependencies for skipped test methods -->

                <i>Method arguments: </i>
                <span class="arguments">
                    "https://api.restful-api.dev/objects", "Sam Sundar", "2024", "03-03-1985", "Delhi 1234", "10000"
                </span>
                <br/>

            <!-- Show logger output for the test -->

                <a href="javascript:toggleElement('exception-3', 'block')"
                   title="Click to expand/collapse">
                    <b>java.lang.AssertionError: expected [200] but found [405]</b>
                </a>
                <br/>
                <div class="stackTrace" id="exception-3">
                        org.testng.Assert.fail(Assert.java:111)<br/>
                        org.testng.Assert.failNotEquals(Assert.java:1578)<br/>
                        org.testng.Assert.assertEqualsImpl(Assert.java:150)<br/>
                        org.testng.Assert.assertEquals(Assert.java:132)<br/>
                        org.testng.Assert.assertEquals(Assert.java:656)<br/>
                        org.testng.Assert.assertEquals(Assert.java:666)<br/>
                        TestNGAssignment.Assignment002.putCallToUpdateAddressOfBankEmployeeDetails_Validation(Assignment002.java:96)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>
                        java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)<br/>
                        java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>
                        java.base/java.lang.reflect.Method.invoke(Method.java:568)<br/>
                        org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)<br/>
                        org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)<br/>
                        org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)<br/>
                        org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)<br/>
                        org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)<br/>
                        org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)<br/>
                        java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br/>
                        org.testng.TestRunner.privateRun(TestRunner.java:819)<br/>
                        org.testng.TestRunner.run(TestRunner.java:619)<br/>
                        org.testng.SuiteRunner.runTest(SuiteRunner.java:443)<br/>
                        org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)<br/>
                        org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)<br/>
                        org.testng.SuiteRunner.run(SuiteRunner.java:336)<br/>
                        org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br/>
                        org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)<br/>
                        org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)<br/>
                        org.testng.TestNG.runSuitesLocally(TestNG.java:1228)<br/>
                        org.testng.TestNG.runSuites(TestNG.java:1134)<br/>
                        org.testng.TestNG.run(TestNG.java:1101)<br/>
                        com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)<br/>
                        com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)<br/>
                </div>
        </td>
    </tr>
    </table>



<script type="text/javascript" src="reportng.js"></script>
</body>
